apiVersion: v1
kind: ServiceAccount
metadata:
  name: solprobe-backend
  namespace: solprobe
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: solprobe-sidecar
  namespace: solprobe
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: solprobe-dashboard
  namespace: solprobe
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: solprobe
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: solprobe
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-pod-reader
  namespace: solprobe
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-pod-reader
  namespace: solprobe
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-pod-reader
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: solprobe
